// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJdMvdAxfAKq7V7ZUvhi6TAoiL_vdey80',
    appId: '1:743667337992:web:5006a80247b0539f73babd',
    messagingSenderId: '743667337992',
    projectId: 'lrtis-b3bac',
    authDomain: 'lrtis-b3bac.firebaseapp.com',
    storageBucket: 'lrtis-b3bac.appspot.com',
    measurementId: 'G-6GMB1176Z9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKSdc4IYj9cXnYQpJNnR6doQMPSd4FhY',
    appId: '1:743667337992:ios:367226967bdd5ea773babd',
    messagingSenderId: '743667337992',
    projectId: 'lrtis-b3bac',
    storageBucket: 'lrtis-b3bac.appspot.com',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbKSdc4IYj9cXnYQpJNnR6doQMPSd4FhY',
    appId: '1:743667337992:ios:367226967bdd5ea773babd',
    messagingSenderId: '743667337992',
    projectId: 'lrtis-b3bac',
    storageBucket: 'lrtis-b3bac.appspot.com',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJdMvdAxfAKq7V7ZUvhi6TAoiL_vdey80',
    appId: '1:743667337992:web:c2b8a087196d2c3b73babd',
    messagingSenderId: '743667337992',
    projectId: 'lrtis-b3bac',
    authDomain: 'lrtis-b3bac.firebaseapp.com',
    storageBucket: 'lrtis-b3bac.appspot.com',
    measurementId: 'G-TH9H04T608',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ckCfpknlqsTIqYyfJG-mGkF-cgTsi4M',
    appId: '1:743667337992:android:a1b6d9dd0f02e1ec73babd',
    messagingSenderId: '743667337992',
    projectId: 'lrtis-b3bac',
    storageBucket: 'lrtis-b3bac.appspot.com',
  );

}